before_install:
  - gem install bundler
bundler_args: "--verbose"
script: "rake test"
rvm:
  - 1.8.7-p371
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - jruby
gemfile:
  - Gemfile
env:
  - MOCHA_OPTIONS=debug
matrix:
  include:
    - rvm: jruby
      gemfile: gemfiles/Gemfile.minitest.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 2.3
      gemfile: gemfiles/Gemfile.minitest.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.minitest.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 2.1
      gemfile: gemfiles/Gemfile.minitest.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.minitest.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.minitest.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.minitest.2.11.2
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.minitest.2.11.0
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.minitest.2.3.0
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.minitest.2.0.1
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.minitest.2.0.0
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.9.3
      gemfile: Gemfile
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.minitest.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.minitest.2.11.2
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.minitest.2.11.0
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.minitest.2.3.0
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.minitest.2.0.1
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.minitest.2.0.0
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.minitest.1.4.2
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.minitest.1.4.0
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.minitest.1.3.0
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=minitest
    - rvm: jruby
      gemfile: gemfiles/Gemfile.test-unit.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 2.3
      gemfile: gemfiles/Gemfile.test-unit.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.test-unit.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 2.1
      gemfile: gemfiles/Gemfile.test-unit.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.test-unit.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.test-unit.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.test-unit.2.0.3
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.test-unit.2.0.1
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.test-unit.2.0.0
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.test-unit.latest
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.test-unit.2.0.3
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.test-unit.2.0.1
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 1.8.7-p371
      gemfile: gemfiles/Gemfile.test-unit.2.0.0
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
    - rvm: 1.8.7-p371
      gemfile: Gemfile
      env: MOCHA_OPTIONS=debug MOCHA_RUN_INTEGRATION_TESTS=test-unit
